// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NAKAMATELEMETRYV1_NAKAMA_V3_H_
#define FLATBUFFERS_GENERATED_NAKAMATELEMETRYV1_NAKAMA_V3_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace nakama {
namespace v3 {

struct Adresse;
struct AdresseBuilder;

struct AbgeleiteteGrenzen;
struct AbgeleiteteGrenzenBuilder;

struct Schleife;
struct SchleifeBuilder;

struct Transportstempel;
struct TransportstempelBuilder;

struct Bandwerte;
struct BandwerteBuilder;

struct Frame;
struct FrameBuilder;

struct QuellenEintrag;
struct QuellenEintragBuilder;

struct FeatureBatch;
struct FeatureBatchBuilder;

enum class Bandgitter : uint8_t {
  unbekannt = 0,
  nakama_1_24_oct_30_18k_v1 = 1,
  nakama_log64_v1 = 2,
  MIN = unbekannt,
  MAX = nakama_log64_v1
};

inline const Bandgitter (&EnumValuesBandgitter())[3] {
  static const Bandgitter values[] = {
    Bandgitter::unbekannt,
    Bandgitter::nakama_1_24_oct_30_18k_v1,
    Bandgitter::nakama_log64_v1
  };
  return values;
}

inline const char * const *EnumNamesBandgitter() {
  static const char * const names[4] = {
    "unbekannt",
    "nakama_1_24_oct_30_18k_v1",
    "nakama_log64_v1",
    nullptr
  };
  return names;
}

inline const char *EnumNameBandgitter(Bandgitter e) {
  if (::flatbuffers::IsOutRange(e, Bandgitter::unbekannt, Bandgitter::nakama_log64_v1)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBandgitter()[index];
}

enum class BandEncoding : uint8_t {
  unbekannt = 0,
  q_db_0p1_i16 = 1,
  q_db_0p01_i16 = 2,
  float32 = 3,
  MIN = unbekannt,
  MAX = float32
};

inline const BandEncoding (&EnumValuesBandEncoding())[4] {
  static const BandEncoding values[] = {
    BandEncoding::unbekannt,
    BandEncoding::q_db_0p1_i16,
    BandEncoding::q_db_0p01_i16,
    BandEncoding::float32
  };
  return values;
}

inline const char * const *EnumNamesBandEncoding() {
  static const char * const names[5] = {
    "unbekannt",
    "q_db_0p1_i16",
    "q_db_0p01_i16",
    "float32",
    nullptr
  };
  return names;
}

inline const char *EnumNameBandEncoding(BandEncoding e) {
  if (::flatbuffers::IsOutRange(e, BandEncoding::unbekannt, BandEncoding::float32)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBandEncoding()[index];
}

enum class Zeitbasis : uint8_t {
  unbekannt = 0,
  project_samples = 1,
  local_monotonic = 2,
  MIN = unbekannt,
  MAX = local_monotonic
};

inline const Zeitbasis (&EnumValuesZeitbasis())[3] {
  static const Zeitbasis values[] = {
    Zeitbasis::unbekannt,
    Zeitbasis::project_samples,
    Zeitbasis::local_monotonic
  };
  return values;
}

inline const char * const *EnumNamesZeitbasis() {
  static const char * const names[4] = {
    "unbekannt",
    "project_samples",
    "local_monotonic",
    nullptr
  };
  return names;
}

inline const char *EnumNameZeitbasis(Zeitbasis e) {
  if (::flatbuffers::IsOutRange(e, Zeitbasis::unbekannt, Zeitbasis::local_monotonic)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesZeitbasis()[index];
}

enum class Herleitung : uint8_t {
  unbekannt = 0,
  validated_block_mapping = 1,
  unproven = 2,
  MIN = unbekannt,
  MAX = unproven
};

inline const Herleitung (&EnumValuesHerleitung())[3] {
  static const Herleitung values[] = {
    Herleitung::unbekannt,
    Herleitung::validated_block_mapping,
    Herleitung::unproven
  };
  return values;
}

inline const char * const *EnumNamesHerleitung() {
  static const char * const names[4] = {
    "unbekannt",
    "validated_block_mapping",
    "unproven",
    nullptr
  };
  return names;
}

inline const char *EnumNameHerleitung(Herleitung e) {
  if (::flatbuffers::IsOutRange(e, Herleitung::unbekannt, Herleitung::unproven)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesHerleitung()[index];
}

enum class Gueltigkeit : uint8_t {
  project_time = 1,
  play_state = 2,
  record_state = 4,
  cycle_bounds = 8,
  continuous_time = 16,
  input_presentation_latency = 32,
  output_presentation_latency = 64,
  NONE = 0,
  ANY = 127
};
FLATBUFFERS_DEFINE_BITMASK_OPERATORS(Gueltigkeit, uint8_t)

inline const Gueltigkeit (&EnumValuesGueltigkeit())[7] {
  static const Gueltigkeit values[] = {
    Gueltigkeit::project_time,
    Gueltigkeit::play_state,
    Gueltigkeit::record_state,
    Gueltigkeit::cycle_bounds,
    Gueltigkeit::continuous_time,
    Gueltigkeit::input_presentation_latency,
    Gueltigkeit::output_presentation_latency
  };
  return values;
}

inline const char *EnumNameGueltigkeit(Gueltigkeit e) {
  switch (e) {
    case Gueltigkeit::project_time: return "project_time";
    case Gueltigkeit::play_state: return "play_state";
    case Gueltigkeit::record_state: return "record_state";
    case Gueltigkeit::cycle_bounds: return "cycle_bounds";
    case Gueltigkeit::continuous_time: return "continuous_time";
    case Gueltigkeit::input_presentation_latency: return "input_presentation_latency";
    case Gueltigkeit::output_presentation_latency: return "output_presentation_latency";
    default: return "";
  }
}

/// Effektive Steueradresse (§32.1). KEIN Feld hier ist additiv: eine unbekannte
/// Eigenschaft waere eine unbekannte Zieladresse. Alle fuenf sind `required` —
/// das prueft schon der FlatBuffers-Verifier, nicht erst unser Leser.
/// Die vier Hex-Token sind je 32 Kleinbuchstaben-Hexziffern (Def. `hex32` des
/// JSON-Vertrags); die SID wird nie geparst, nur verglichen.
struct Adresse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AdresseBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LOGON_SID = 4,
    VT_PROJECT_BINDING_ID = 6,
    VT_SESSION_EPOCH = 8,
    VT_INSTANCE_ID = 10,
    VT_RUNTIME_NONCE = 12
  };
  const ::flatbuffers::String *logon_sid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LOGON_SID);
  }
  const ::flatbuffers::String *project_binding_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROJECT_BINDING_ID);
  }
  const ::flatbuffers::String *session_epoch() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SESSION_EPOCH);
  }
  const ::flatbuffers::String *instance_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INSTANCE_ID);
  }
  const ::flatbuffers::String *runtime_nonce() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RUNTIME_NONCE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_LOGON_SID) &&
           verifier.VerifyString(logon_sid()) &&
           VerifyOffsetRequired(verifier, VT_PROJECT_BINDING_ID) &&
           verifier.VerifyString(project_binding_id()) &&
           VerifyOffsetRequired(verifier, VT_SESSION_EPOCH) &&
           verifier.VerifyString(session_epoch()) &&
           VerifyOffsetRequired(verifier, VT_INSTANCE_ID) &&
           verifier.VerifyString(instance_id()) &&
           VerifyOffsetRequired(verifier, VT_RUNTIME_NONCE) &&
           verifier.VerifyString(runtime_nonce()) &&
           verifier.EndTable();
  }
};

struct AdresseBuilder {
  typedef Adresse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_logon_sid(::flatbuffers::Offset<::flatbuffers::String> logon_sid) {
    fbb_.AddOffset(Adresse::VT_LOGON_SID, logon_sid);
  }
  void add_project_binding_id(::flatbuffers::Offset<::flatbuffers::String> project_binding_id) {
    fbb_.AddOffset(Adresse::VT_PROJECT_BINDING_ID, project_binding_id);
  }
  void add_session_epoch(::flatbuffers::Offset<::flatbuffers::String> session_epoch) {
    fbb_.AddOffset(Adresse::VT_SESSION_EPOCH, session_epoch);
  }
  void add_instance_id(::flatbuffers::Offset<::flatbuffers::String> instance_id) {
    fbb_.AddOffset(Adresse::VT_INSTANCE_ID, instance_id);
  }
  void add_runtime_nonce(::flatbuffers::Offset<::flatbuffers::String> runtime_nonce) {
    fbb_.AddOffset(Adresse::VT_RUNTIME_NONCE, runtime_nonce);
  }
  explicit AdresseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Adresse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Adresse>(end);
    fbb_.Required(o, Adresse::VT_LOGON_SID);
    fbb_.Required(o, Adresse::VT_PROJECT_BINDING_ID);
    fbb_.Required(o, Adresse::VT_SESSION_EPOCH);
    fbb_.Required(o, Adresse::VT_INSTANCE_ID);
    fbb_.Required(o, Adresse::VT_RUNTIME_NONCE);
    return o;
  }
};

inline ::flatbuffers::Offset<Adresse> CreateAdresse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> logon_sid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> project_binding_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> session_epoch = 0,
    ::flatbuffers::Offset<::flatbuffers::String> instance_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> runtime_nonce = 0) {
  AdresseBuilder builder_(_fbb);
  builder_.add_runtime_nonce(runtime_nonce);
  builder_.add_instance_id(instance_id);
  builder_.add_session_epoch(session_epoch);
  builder_.add_project_binding_id(project_binding_id);
  builder_.add_logon_sid(logon_sid);
  return builder_.Finish();
}

struct Adresse::Traits {
  using type = Adresse;
  static auto constexpr Create = CreateAdresse;
};

inline ::flatbuffers::Offset<Adresse> CreateAdresseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *logon_sid = nullptr,
    const char *project_binding_id = nullptr,
    const char *session_epoch = nullptr,
    const char *instance_id = nullptr,
    const char *runtime_nonce = nullptr) {
  auto logon_sid__ = logon_sid ? _fbb.CreateString(logon_sid) : 0;
  auto project_binding_id__ = project_binding_id ? _fbb.CreateString(project_binding_id) : 0;
  auto session_epoch__ = session_epoch ? _fbb.CreateString(session_epoch) : 0;
  auto instance_id__ = instance_id ? _fbb.CreateString(instance_id) : 0;
  auto runtime_nonce__ = runtime_nonce ? _fbb.CreateString(runtime_nonce) : 0;
  return nakama::v3::CreateAdresse(
      _fbb,
      logon_sid__,
      project_binding_id__,
      session_epoch__,
      instance_id__,
      runtime_nonce__);
}

/// Abgeleitete Samplegrenzen einer Schleife. NUR gueltig, wenn PPQ, Projektzeit
/// und Tempo im Block eine durch FL-Goldens validierte Abbildung erlauben
/// (§32.3) — deshalb traegt das Objekt seine Herleitung mit, statt sie dem
/// Empfaenger zu ueberlassen.
struct AbgeleiteteGrenzen FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AbgeleiteteGrenzenBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_START = 4,
    VT_ENDE = 6,
    VT_HERLEITUNG = 8
  };
  int64_t start() const {
    return GetField<int64_t>(VT_START, 0);
  }
  int64_t ende() const {
    return GetField<int64_t>(VT_ENDE, 0);
  }
  nakama::v3::Herleitung herleitung() const {
    return static_cast<nakama::v3::Herleitung>(GetField<uint8_t>(VT_HERLEITUNG, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_START, 8) &&
           VerifyField<int64_t>(verifier, VT_ENDE, 8) &&
           VerifyField<uint8_t>(verifier, VT_HERLEITUNG, 1) &&
           verifier.EndTable();
  }
};

struct AbgeleiteteGrenzenBuilder {
  typedef AbgeleiteteGrenzen Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_start(int64_t start) {
    fbb_.AddElement<int64_t>(AbgeleiteteGrenzen::VT_START, start, 0);
  }
  void add_ende(int64_t ende) {
    fbb_.AddElement<int64_t>(AbgeleiteteGrenzen::VT_ENDE, ende, 0);
  }
  void add_herleitung(nakama::v3::Herleitung herleitung) {
    fbb_.AddElement<uint8_t>(AbgeleiteteGrenzen::VT_HERLEITUNG, static_cast<uint8_t>(herleitung), 0);
  }
  explicit AbgeleiteteGrenzenBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AbgeleiteteGrenzen> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AbgeleiteteGrenzen>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AbgeleiteteGrenzen> CreateAbgeleiteteGrenzen(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t start = 0,
    int64_t ende = 0,
    nakama::v3::Herleitung herleitung = nakama::v3::Herleitung::unbekannt) {
  AbgeleiteteGrenzenBuilder builder_(_fbb);
  builder_.add_ende(ende);
  builder_.add_start(start);
  builder_.add_herleitung(herleitung);
  return builder_.Finish();
}

struct AbgeleiteteGrenzen::Traits {
  using type = AbgeleiteteGrenzen;
  static auto constexpr Create = CreateAbgeleiteteGrenzen;
};

/// Schleifengrenzen. VST3 liefert sie als PPQ; Samplegrenzen sind ABGELEITET.
/// `active` und `bounds_valid` sind bool ohne Optionalitaet: ihr Default false
/// ist die richtige Bedeutung eines fehlenden Feldes (§32.3).
struct Schleife FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SchleifeBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACTIVE = 4,
    VT_BOUNDS_VALID = 6,
    VT_START_PPQ = 8,
    VT_END_PPQ = 10,
    VT_ABGELEITETE_GRENZEN = 12
  };
  bool active() const {
    return GetField<uint8_t>(VT_ACTIVE, 0) != 0;
  }
  bool bounds_valid() const {
    return GetField<uint8_t>(VT_BOUNDS_VALID, 0) != 0;
  }
  ::flatbuffers::Optional<double> start_ppq() const {
    return GetOptional<double, double>(VT_START_PPQ);
  }
  ::flatbuffers::Optional<double> end_ppq() const {
    return GetOptional<double, double>(VT_END_PPQ);
  }
  const nakama::v3::AbgeleiteteGrenzen *abgeleitete_grenzen() const {
    return GetPointer<const nakama::v3::AbgeleiteteGrenzen *>(VT_ABGELEITETE_GRENZEN);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_ACTIVE, 1) &&
           VerifyField<uint8_t>(verifier, VT_BOUNDS_VALID, 1) &&
           VerifyField<double>(verifier, VT_START_PPQ, 8) &&
           VerifyField<double>(verifier, VT_END_PPQ, 8) &&
           VerifyOffset(verifier, VT_ABGELEITETE_GRENZEN) &&
           verifier.VerifyTable(abgeleitete_grenzen()) &&
           verifier.EndTable();
  }
};

struct SchleifeBuilder {
  typedef Schleife Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_active(bool active) {
    fbb_.AddElement<uint8_t>(Schleife::VT_ACTIVE, static_cast<uint8_t>(active), 0);
  }
  void add_bounds_valid(bool bounds_valid) {
    fbb_.AddElement<uint8_t>(Schleife::VT_BOUNDS_VALID, static_cast<uint8_t>(bounds_valid), 0);
  }
  void add_start_ppq(double start_ppq) {
    fbb_.AddElement<double>(Schleife::VT_START_PPQ, start_ppq);
  }
  void add_end_ppq(double end_ppq) {
    fbb_.AddElement<double>(Schleife::VT_END_PPQ, end_ppq);
  }
  void add_abgeleitete_grenzen(::flatbuffers::Offset<nakama::v3::AbgeleiteteGrenzen> abgeleitete_grenzen) {
    fbb_.AddOffset(Schleife::VT_ABGELEITETE_GRENZEN, abgeleitete_grenzen);
  }
  explicit SchleifeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Schleife> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Schleife>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Schleife> CreateSchleife(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool active = false,
    bool bounds_valid = false,
    ::flatbuffers::Optional<double> start_ppq = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<double> end_ppq = ::flatbuffers::nullopt,
    ::flatbuffers::Offset<nakama::v3::AbgeleiteteGrenzen> abgeleitete_grenzen = 0) {
  SchleifeBuilder builder_(_fbb);
  if(end_ppq) { builder_.add_end_ppq(*end_ppq); }
  if(start_ppq) { builder_.add_start_ppq(*start_ppq); }
  builder_.add_abgeleitete_grenzen(abgeleitete_grenzen);
  builder_.add_bounds_valid(bounds_valid);
  builder_.add_active(active);
  return builder_.Finish();
}

struct Schleife::Traits {
  using type = Schleife;
  static auto constexpr Create = CreateSchleife;
};

/// Zeitbasis und explizite Gueltigkeit jedes zeitabhaengigen Frames (§32.3).
///
/// Die drei `= null`-Felder sind echte FlatBuffers-Optionals: bei ihnen ist
/// "nicht gemeldet" von "gemeldet als 0" unterscheidbar. Bei
/// `project_sample_start` ist das keine Feinheit — 0 ist eine voellig normale
/// Projektposition, und ein Default 0 haette den Frameanfang stillschweigend
/// an den Songanfang gelegt.
struct Transportstempel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransportstempelBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSPORT_EPOCH = 4,
    VT_CONTINUITY_SEGMENT = 6,
    VT_SEQUENCE = 8,
    VT_ZEITBASIS = 10,
    VT_PROJECT_SAMPLE_START = 12,
    VT_SAMPLE_COUNT = 14,
    VT_SAMPLE_RATE = 16,
    VT_PLAYING = 18,
    VT_RECORDING = 20,
    VT_CONTINUOUS_TIME_SAMPLES = 22,
    VT_SCHLEIFE = 24,
    VT_INPUT_PRESENTATION_LATENCY = 26,
    VT_OUTPUT_PRESENTATION_LATENCY = 28,
    VT_GUELTIGKEIT = 30,
    VT_PROCESS_CONTEXT_PRESENT = 32
  };
  uint64_t transport_epoch() const {
    return GetField<uint64_t>(VT_TRANSPORT_EPOCH, 0);
  }
  uint64_t continuity_segment() const {
    return GetField<uint64_t>(VT_CONTINUITY_SEGMENT, 0);
  }
  uint64_t sequence() const {
    return GetField<uint64_t>(VT_SEQUENCE, 0);
  }
  nakama::v3::Zeitbasis zeitbasis() const {
    return static_cast<nakama::v3::Zeitbasis>(GetField<uint8_t>(VT_ZEITBASIS, 0));
  }
  ::flatbuffers::Optional<int64_t> project_sample_start() const {
    return GetOptional<int64_t, int64_t>(VT_PROJECT_SAMPLE_START);
  }
  uint32_t sample_count() const {
    return GetField<uint32_t>(VT_SAMPLE_COUNT, 0);
  }
  double sample_rate() const {
    return GetField<double>(VT_SAMPLE_RATE, 0.0);
  }
  bool playing() const {
    return GetField<uint8_t>(VT_PLAYING, 0) != 0;
  }
  bool recording() const {
    return GetField<uint8_t>(VT_RECORDING, 0) != 0;
  }
  ::flatbuffers::Optional<int64_t> continuous_time_samples() const {
    return GetOptional<int64_t, int64_t>(VT_CONTINUOUS_TIME_SAMPLES);
  }
  const nakama::v3::Schleife *schleife() const {
    return GetPointer<const nakama::v3::Schleife *>(VT_SCHLEIFE);
  }
  ::flatbuffers::Optional<uint32_t> input_presentation_latency() const {
    return GetOptional<uint32_t, uint32_t>(VT_INPUT_PRESENTATION_LATENCY);
  }
  ::flatbuffers::Optional<uint32_t> output_presentation_latency() const {
    return GetOptional<uint32_t, uint32_t>(VT_OUTPUT_PRESENTATION_LATENCY);
  }
  nakama::v3::Gueltigkeit gueltigkeit() const {
    return static_cast<nakama::v3::Gueltigkeit>(GetField<uint8_t>(VT_GUELTIGKEIT, 0));
  }
  /// §32.3 woertlich: "Die Wrapper-Bridge liefert deshalb
  /// process_context_present und unabhaengige Validity-Bits; ohne Bridge gilt
  /// Projektzeit als unbewiesen."
  ///
  /// OPTIONAL und nicht `bool` mit Default false: ein Default machte "der
  /// Sender hat das Feld weggelassen" ununterscheidbar von "der Host hat
  /// keinen Context angelegt". Der Leser verlangt es. Und es ist bewusst KEIN
  /// Gueltigkeitsbit - es beschreibt nicht die Gueltigkeit EINES Feldes,
  /// sondern ob der Host ueberhaupt eine Zeitquelle bereitgestellt hat.
  ::flatbuffers::Optional<bool> process_context_present() const {
    return GetOptional<uint8_t, bool>(VT_PROCESS_CONTEXT_PRESENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TRANSPORT_EPOCH, 8) &&
           VerifyField<uint64_t>(verifier, VT_CONTINUITY_SEGMENT, 8) &&
           VerifyField<uint64_t>(verifier, VT_SEQUENCE, 8) &&
           VerifyField<uint8_t>(verifier, VT_ZEITBASIS, 1) &&
           VerifyField<int64_t>(verifier, VT_PROJECT_SAMPLE_START, 8) &&
           VerifyField<uint32_t>(verifier, VT_SAMPLE_COUNT, 4) &&
           VerifyField<double>(verifier, VT_SAMPLE_RATE, 8) &&
           VerifyField<uint8_t>(verifier, VT_PLAYING, 1) &&
           VerifyField<uint8_t>(verifier, VT_RECORDING, 1) &&
           VerifyField<int64_t>(verifier, VT_CONTINUOUS_TIME_SAMPLES, 8) &&
           VerifyOffset(verifier, VT_SCHLEIFE) &&
           verifier.VerifyTable(schleife()) &&
           VerifyField<uint32_t>(verifier, VT_INPUT_PRESENTATION_LATENCY, 4) &&
           VerifyField<uint32_t>(verifier, VT_OUTPUT_PRESENTATION_LATENCY, 4) &&
           VerifyField<uint8_t>(verifier, VT_GUELTIGKEIT, 1) &&
           VerifyField<uint8_t>(verifier, VT_PROCESS_CONTEXT_PRESENT, 1) &&
           verifier.EndTable();
  }
};

struct TransportstempelBuilder {
  typedef Transportstempel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transport_epoch(uint64_t transport_epoch) {
    fbb_.AddElement<uint64_t>(Transportstempel::VT_TRANSPORT_EPOCH, transport_epoch, 0);
  }
  void add_continuity_segment(uint64_t continuity_segment) {
    fbb_.AddElement<uint64_t>(Transportstempel::VT_CONTINUITY_SEGMENT, continuity_segment, 0);
  }
  void add_sequence(uint64_t sequence) {
    fbb_.AddElement<uint64_t>(Transportstempel::VT_SEQUENCE, sequence, 0);
  }
  void add_zeitbasis(nakama::v3::Zeitbasis zeitbasis) {
    fbb_.AddElement<uint8_t>(Transportstempel::VT_ZEITBASIS, static_cast<uint8_t>(zeitbasis), 0);
  }
  void add_project_sample_start(int64_t project_sample_start) {
    fbb_.AddElement<int64_t>(Transportstempel::VT_PROJECT_SAMPLE_START, project_sample_start);
  }
  void add_sample_count(uint32_t sample_count) {
    fbb_.AddElement<uint32_t>(Transportstempel::VT_SAMPLE_COUNT, sample_count, 0);
  }
  void add_sample_rate(double sample_rate) {
    fbb_.AddElement<double>(Transportstempel::VT_SAMPLE_RATE, sample_rate, 0.0);
  }
  void add_playing(bool playing) {
    fbb_.AddElement<uint8_t>(Transportstempel::VT_PLAYING, static_cast<uint8_t>(playing), 0);
  }
  void add_recording(bool recording) {
    fbb_.AddElement<uint8_t>(Transportstempel::VT_RECORDING, static_cast<uint8_t>(recording), 0);
  }
  void add_continuous_time_samples(int64_t continuous_time_samples) {
    fbb_.AddElement<int64_t>(Transportstempel::VT_CONTINUOUS_TIME_SAMPLES, continuous_time_samples);
  }
  void add_schleife(::flatbuffers::Offset<nakama::v3::Schleife> schleife) {
    fbb_.AddOffset(Transportstempel::VT_SCHLEIFE, schleife);
  }
  void add_input_presentation_latency(uint32_t input_presentation_latency) {
    fbb_.AddElement<uint32_t>(Transportstempel::VT_INPUT_PRESENTATION_LATENCY, input_presentation_latency);
  }
  void add_output_presentation_latency(uint32_t output_presentation_latency) {
    fbb_.AddElement<uint32_t>(Transportstempel::VT_OUTPUT_PRESENTATION_LATENCY, output_presentation_latency);
  }
  void add_gueltigkeit(nakama::v3::Gueltigkeit gueltigkeit) {
    fbb_.AddElement<uint8_t>(Transportstempel::VT_GUELTIGKEIT, static_cast<uint8_t>(gueltigkeit), 0);
  }
  void add_process_context_present(bool process_context_present) {
    fbb_.AddElement<uint8_t>(Transportstempel::VT_PROCESS_CONTEXT_PRESENT, static_cast<uint8_t>(process_context_present));
  }
  explicit TransportstempelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Transportstempel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Transportstempel>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Transportstempel> CreateTransportstempel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t transport_epoch = 0,
    uint64_t continuity_segment = 0,
    uint64_t sequence = 0,
    nakama::v3::Zeitbasis zeitbasis = nakama::v3::Zeitbasis::unbekannt,
    ::flatbuffers::Optional<int64_t> project_sample_start = ::flatbuffers::nullopt,
    uint32_t sample_count = 0,
    double sample_rate = 0.0,
    bool playing = false,
    bool recording = false,
    ::flatbuffers::Optional<int64_t> continuous_time_samples = ::flatbuffers::nullopt,
    ::flatbuffers::Offset<nakama::v3::Schleife> schleife = 0,
    ::flatbuffers::Optional<uint32_t> input_presentation_latency = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint32_t> output_presentation_latency = ::flatbuffers::nullopt,
    nakama::v3::Gueltigkeit gueltigkeit = static_cast<nakama::v3::Gueltigkeit>(0),
    ::flatbuffers::Optional<bool> process_context_present = ::flatbuffers::nullopt) {
  TransportstempelBuilder builder_(_fbb);
  if(continuous_time_samples) { builder_.add_continuous_time_samples(*continuous_time_samples); }
  builder_.add_sample_rate(sample_rate);
  if(project_sample_start) { builder_.add_project_sample_start(*project_sample_start); }
  builder_.add_sequence(sequence);
  builder_.add_continuity_segment(continuity_segment);
  builder_.add_transport_epoch(transport_epoch);
  if(output_presentation_latency) { builder_.add_output_presentation_latency(*output_presentation_latency); }
  if(input_presentation_latency) { builder_.add_input_presentation_latency(*input_presentation_latency); }
  builder_.add_schleife(schleife);
  builder_.add_sample_count(sample_count);
  if(process_context_present) { builder_.add_process_context_present(*process_context_present); }
  builder_.add_gueltigkeit(gueltigkeit);
  builder_.add_recording(recording);
  builder_.add_playing(playing);
  builder_.add_zeitbasis(zeitbasis);
  return builder_.Finish();
}

struct Transportstempel::Traits {
  using type = Transportstempel;
  static auto constexpr Create = CreateTransportstempel;
};

/// Ein Bandsatz mit seinem Gitter, seiner Kodierung, seiner Gueltigkeitsbitmap
/// und seinem Saettigungsbit (§33.1). Gegenstueck zu `$defs/bandwerte` im
/// JSON-Vertrag; Skalierung und Rundung stehen in quantisierung-v1.json.
///
/// Die Kodierung steht IM Batch und wird nie aus dem Nachrichtentyp geraten
/// (§33.1 woertlich). Genau zwei Traeger existieren: `werte_i16` fuer beide
/// q_db-Kodierungen, `werte_f32` fuer float32. Der Leser erzwingt, dass genau
/// EINER gesetzt ist und dass er zur Kodierung passt — ein Puffer mit
/// encoding=float32 und gesetztem `werte_i16` ist ungueltig, nicht "irgendwie
/// interpretierbar".
///
/// `gueltig_bitmap` ist LSB-first ueber ceil(n/8) Bytes: Band i sitzt in Byte
/// i/8, Bit i%8. Die Fuellbits des letzten Bytes MUESSEN 0 sein — sonst
/// erzeugen zwei Sender fuer denselben Messwert zwei verschiedene Puffer, und
/// ein Bytevergleich waere keine Aussage mehr.
struct Bandwerte FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BandwerteBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GITTER = 4,
    VT_ENCODING = 6,
    VT_WERTE_I16 = 8,
    VT_WERTE_F32 = 10,
    VT_GUELTIG_BITMAP = 12,
    VT_SATURATED = 14
  };
  nakama::v3::Bandgitter gitter() const {
    return static_cast<nakama::v3::Bandgitter>(GetField<uint8_t>(VT_GITTER, 0));
  }
  nakama::v3::BandEncoding encoding() const {
    return static_cast<nakama::v3::BandEncoding>(GetField<uint8_t>(VT_ENCODING, 0));
  }
  const ::flatbuffers::Vector<int16_t> *werte_i16() const {
    return GetPointer<const ::flatbuffers::Vector<int16_t> *>(VT_WERTE_I16);
  }
  const ::flatbuffers::Vector<float> *werte_f32() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_WERTE_F32);
  }
  const ::flatbuffers::Vector<uint8_t> *gueltig_bitmap() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_GUELTIG_BITMAP);
  }
  bool saturated() const {
    return GetField<uint8_t>(VT_SATURATED, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_GITTER, 1) &&
           VerifyField<uint8_t>(verifier, VT_ENCODING, 1) &&
           VerifyOffset(verifier, VT_WERTE_I16) &&
           verifier.VerifyVector(werte_i16()) &&
           VerifyOffset(verifier, VT_WERTE_F32) &&
           verifier.VerifyVector(werte_f32()) &&
           VerifyOffsetRequired(verifier, VT_GUELTIG_BITMAP) &&
           verifier.VerifyVector(gueltig_bitmap()) &&
           VerifyField<uint8_t>(verifier, VT_SATURATED, 1) &&
           verifier.EndTable();
  }
};

struct BandwerteBuilder {
  typedef Bandwerte Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_gitter(nakama::v3::Bandgitter gitter) {
    fbb_.AddElement<uint8_t>(Bandwerte::VT_GITTER, static_cast<uint8_t>(gitter), 0);
  }
  void add_encoding(nakama::v3::BandEncoding encoding) {
    fbb_.AddElement<uint8_t>(Bandwerte::VT_ENCODING, static_cast<uint8_t>(encoding), 0);
  }
  void add_werte_i16(::flatbuffers::Offset<::flatbuffers::Vector<int16_t>> werte_i16) {
    fbb_.AddOffset(Bandwerte::VT_WERTE_I16, werte_i16);
  }
  void add_werte_f32(::flatbuffers::Offset<::flatbuffers::Vector<float>> werte_f32) {
    fbb_.AddOffset(Bandwerte::VT_WERTE_F32, werte_f32);
  }
  void add_gueltig_bitmap(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> gueltig_bitmap) {
    fbb_.AddOffset(Bandwerte::VT_GUELTIG_BITMAP, gueltig_bitmap);
  }
  void add_saturated(bool saturated) {
    fbb_.AddElement<uint8_t>(Bandwerte::VT_SATURATED, static_cast<uint8_t>(saturated), 0);
  }
  explicit BandwerteBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Bandwerte> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Bandwerte>(end);
    fbb_.Required(o, Bandwerte::VT_GUELTIG_BITMAP);
    return o;
  }
};

inline ::flatbuffers::Offset<Bandwerte> CreateBandwerte(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    nakama::v3::Bandgitter gitter = nakama::v3::Bandgitter::unbekannt,
    nakama::v3::BandEncoding encoding = nakama::v3::BandEncoding::unbekannt,
    ::flatbuffers::Offset<::flatbuffers::Vector<int16_t>> werte_i16 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> werte_f32 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> gueltig_bitmap = 0,
    bool saturated = false) {
  BandwerteBuilder builder_(_fbb);
  builder_.add_gueltig_bitmap(gueltig_bitmap);
  builder_.add_werte_f32(werte_f32);
  builder_.add_werte_i16(werte_i16);
  builder_.add_saturated(saturated);
  builder_.add_encoding(encoding);
  builder_.add_gitter(gitter);
  return builder_.Finish();
}

struct Bandwerte::Traits {
  using type = Bandwerte;
  static auto constexpr Create = CreateBandwerte;
};

inline ::flatbuffers::Offset<Bandwerte> CreateBandwerteDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    nakama::v3::Bandgitter gitter = nakama::v3::Bandgitter::unbekannt,
    nakama::v3::BandEncoding encoding = nakama::v3::BandEncoding::unbekannt,
    const std::vector<int16_t> *werte_i16 = nullptr,
    const std::vector<float> *werte_f32 = nullptr,
    const std::vector<uint8_t> *gueltig_bitmap = nullptr,
    bool saturated = false) {
  auto werte_i16__ = werte_i16 ? _fbb.CreateVector<int16_t>(*werte_i16) : 0;
  auto werte_f32__ = werte_f32 ? _fbb.CreateVector<float>(*werte_f32) : 0;
  auto gueltig_bitmap__ = gueltig_bitmap ? _fbb.CreateVector<uint8_t>(*gueltig_bitmap) : 0;
  return nakama::v3::CreateBandwerte(
      _fbb,
      gitter,
      encoding,
      werte_i16__,
      werte_f32__,
      gueltig_bitmap__,
      saturated);
}

/// Ein Messframe EINER Quelle (§33.2, Live-Telemetrie 10 Hz).
///
/// Alle Kennzahlen sind Optionals. Das ist die NaN-Ehrlichkeit dieses Projekts
/// im Binaerformat: ein nicht messbarer Wert wird WEGGELASSEN, nicht als 0 oder
/// als NaN gesendet. Ein NaN oder ±inf auf der Leitung ist deshalb ein
/// Senderfehler und wird von beiden Beinen abgelehnt statt sanitisiert —
/// quantisierung-v1.json legt fest, dass Nichtendliches beim ERZEUGEN in
/// Wert 0 mit gueltig=false uebersetzt wird.
struct Frame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FrameBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRANSPORT = 4,
    VT_BAENDER = 6,
    VT_METRICS_VERSION = 8,
    VT_AKTIVITAET = 10,
    VT_LUFS_S = 12,
    VT_PEAK_DB = 14,
    VT_CREST_DB = 16,
    VT_PSR_DB = 18,
    VT_BREITE = 20,
    VT_KORRELATION = 22,
    VT_BAND_STEREO = 24
  };
  const nakama::v3::Transportstempel *transport() const {
    return GetPointer<const nakama::v3::Transportstempel *>(VT_TRANSPORT);
  }
  const nakama::v3::Bandwerte *baender() const {
    return GetPointer<const nakama::v3::Bandwerte *>(VT_BAENDER);
  }
  uint32_t metrics_version() const {
    return GetField<uint32_t>(VT_METRICS_VERSION, 0);
  }
  ::flatbuffers::Optional<float> aktivitaet() const {
    return GetOptional<float, float>(VT_AKTIVITAET);
  }
  ::flatbuffers::Optional<float> lufs_s() const {
    return GetOptional<float, float>(VT_LUFS_S);
  }
  ::flatbuffers::Optional<float> peak_db() const {
    return GetOptional<float, float>(VT_PEAK_DB);
  }
  ::flatbuffers::Optional<float> crest_db() const {
    return GetOptional<float, float>(VT_CREST_DB);
  }
  ::flatbuffers::Optional<float> psr_db() const {
    return GetOptional<float, float>(VT_PSR_DB);
  }
  ::flatbuffers::Optional<float> breite() const {
    return GetOptional<float, float>(VT_BREITE);
  }
  ::flatbuffers::Optional<float> korrelation() const {
    return GetOptional<float, float>(VT_KORRELATION);
  }
  /// Optionale Band-Stereobreite auf dem festen 64er-Loggitter. Sie ist ein
  /// eigener Bandsatz, nie eine Umdeutung von `breite`: float32, 64 Werte,
  /// acht Bitmapbytes, gueltige Werte im Bereich [0, 1], saturated=false.
  const nakama::v3::Bandwerte *band_stereo() const {
    return GetPointer<const nakama::v3::Bandwerte *>(VT_BAND_STEREO);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TRANSPORT) &&
           verifier.VerifyTable(transport()) &&
           VerifyOffsetRequired(verifier, VT_BAENDER) &&
           verifier.VerifyTable(baender()) &&
           VerifyField<uint32_t>(verifier, VT_METRICS_VERSION, 4) &&
           VerifyField<float>(verifier, VT_AKTIVITAET, 4) &&
           VerifyField<float>(verifier, VT_LUFS_S, 4) &&
           VerifyField<float>(verifier, VT_PEAK_DB, 4) &&
           VerifyField<float>(verifier, VT_CREST_DB, 4) &&
           VerifyField<float>(verifier, VT_PSR_DB, 4) &&
           VerifyField<float>(verifier, VT_BREITE, 4) &&
           VerifyField<float>(verifier, VT_KORRELATION, 4) &&
           VerifyOffset(verifier, VT_BAND_STEREO) &&
           verifier.VerifyTable(band_stereo()) &&
           verifier.EndTable();
  }
};

struct FrameBuilder {
  typedef Frame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_transport(::flatbuffers::Offset<nakama::v3::Transportstempel> transport) {
    fbb_.AddOffset(Frame::VT_TRANSPORT, transport);
  }
  void add_baender(::flatbuffers::Offset<nakama::v3::Bandwerte> baender) {
    fbb_.AddOffset(Frame::VT_BAENDER, baender);
  }
  void add_metrics_version(uint32_t metrics_version) {
    fbb_.AddElement<uint32_t>(Frame::VT_METRICS_VERSION, metrics_version, 0);
  }
  void add_aktivitaet(float aktivitaet) {
    fbb_.AddElement<float>(Frame::VT_AKTIVITAET, aktivitaet);
  }
  void add_lufs_s(float lufs_s) {
    fbb_.AddElement<float>(Frame::VT_LUFS_S, lufs_s);
  }
  void add_peak_db(float peak_db) {
    fbb_.AddElement<float>(Frame::VT_PEAK_DB, peak_db);
  }
  void add_crest_db(float crest_db) {
    fbb_.AddElement<float>(Frame::VT_CREST_DB, crest_db);
  }
  void add_psr_db(float psr_db) {
    fbb_.AddElement<float>(Frame::VT_PSR_DB, psr_db);
  }
  void add_breite(float breite) {
    fbb_.AddElement<float>(Frame::VT_BREITE, breite);
  }
  void add_korrelation(float korrelation) {
    fbb_.AddElement<float>(Frame::VT_KORRELATION, korrelation);
  }
  void add_band_stereo(::flatbuffers::Offset<nakama::v3::Bandwerte> band_stereo) {
    fbb_.AddOffset(Frame::VT_BAND_STEREO, band_stereo);
  }
  explicit FrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Frame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Frame>(end);
    fbb_.Required(o, Frame::VT_TRANSPORT);
    fbb_.Required(o, Frame::VT_BAENDER);
    return o;
  }
};

inline ::flatbuffers::Offset<Frame> CreateFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<nakama::v3::Transportstempel> transport = 0,
    ::flatbuffers::Offset<nakama::v3::Bandwerte> baender = 0,
    uint32_t metrics_version = 0,
    ::flatbuffers::Optional<float> aktivitaet = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<float> lufs_s = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<float> peak_db = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<float> crest_db = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<float> psr_db = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<float> breite = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<float> korrelation = ::flatbuffers::nullopt,
    ::flatbuffers::Offset<nakama::v3::Bandwerte> band_stereo = 0) {
  FrameBuilder builder_(_fbb);
  builder_.add_band_stereo(band_stereo);
  if(korrelation) { builder_.add_korrelation(*korrelation); }
  if(breite) { builder_.add_breite(*breite); }
  if(psr_db) { builder_.add_psr_db(*psr_db); }
  if(crest_db) { builder_.add_crest_db(*crest_db); }
  if(peak_db) { builder_.add_peak_db(*peak_db); }
  if(lufs_s) { builder_.add_lufs_s(*lufs_s); }
  if(aktivitaet) { builder_.add_aktivitaet(*aktivitaet); }
  builder_.add_metrics_version(metrics_version);
  builder_.add_baender(baender);
  builder_.add_transport(transport);
  return builder_.Finish();
}

struct Frame::Traits {
  using type = Frame;
  static auto constexpr Create = CreateFrame;
};

/// Ein Eintrag des Batches: genau eine Quelle mit genau ihrem aktuellen Frame.
struct QuellenEintrag FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef QuellenEintragBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_QUELLE = 4,
    VT_FRAME = 6
  };
  const nakama::v3::Adresse *quelle() const {
    return GetPointer<const nakama::v3::Adresse *>(VT_QUELLE);
  }
  const nakama::v3::Frame *frame() const {
    return GetPointer<const nakama::v3::Frame *>(VT_FRAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_QUELLE) &&
           verifier.VerifyTable(quelle()) &&
           VerifyOffsetRequired(verifier, VT_FRAME) &&
           verifier.VerifyTable(frame()) &&
           verifier.EndTable();
  }
};

struct QuellenEintragBuilder {
  typedef QuellenEintrag Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_quelle(::flatbuffers::Offset<nakama::v3::Adresse> quelle) {
    fbb_.AddOffset(QuellenEintrag::VT_QUELLE, quelle);
  }
  void add_frame(::flatbuffers::Offset<nakama::v3::Frame> frame) {
    fbb_.AddOffset(QuellenEintrag::VT_FRAME, frame);
  }
  explicit QuellenEintragBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<QuellenEintrag> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<QuellenEintrag>(end);
    fbb_.Required(o, QuellenEintrag::VT_QUELLE);
    fbb_.Required(o, QuellenEintrag::VT_FRAME);
    return o;
  }
};

inline ::flatbuffers::Offset<QuellenEintrag> CreateQuellenEintrag(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<nakama::v3::Adresse> quelle = 0,
    ::flatbuffers::Offset<nakama::v3::Frame> frame = 0) {
  QuellenEintragBuilder builder_(_fbb);
  builder_.add_frame(frame);
  builder_.add_quelle(quelle);
  return builder_.Finish();
}

struct QuellenEintrag::Traits {
  using type = QuellenEintrag;
  static auto constexpr Create = CreateQuellenEintrag;
};

/// Der Wurzeltyp (§33.1, Pruefbericht Befund D):
///
///   "Ein `FeatureBatch` ist eine Liste von `(source, frame)`-Eintraegen mit
///    hoechstens EINEM aktuellen Frame je Quelle. Sonde→Broker ist der
///    Sonderfall mit genau einem Eintrag (Queuecap 2, replace-oldest);
///    nur Broker→Main buendelt die aktuellen Frames mehrerer Sonden."
///
/// Daraus folgt die Regel, die kein Schema ausdruecken kann und deshalb beide
/// Leser tragen: ZWEI EINTRAEGE MIT DERSELBEN `instance_id` SIND UNGUELTIG.
/// Genau deshalb braucht das Format keine zweite Wrapper-Ebene.
///
/// Die Tabelle haelt heute ein einziges Feld. Das ist Absicht und kein
/// Platzhalter: als Tabelle (statt als blosser Vektor-Wurzeltyp) kann sie
/// spaeter Felder bekommen, ohne dass ein alter Leser bricht.
struct FeatureBatch FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FeatureBatchBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EINTRAEGE = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<nakama::v3::QuellenEintrag>> *eintraege() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<nakama::v3::QuellenEintrag>> *>(VT_EINTRAEGE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_EINTRAEGE) &&
           verifier.VerifyVector(eintraege()) &&
           verifier.VerifyVectorOfTables(eintraege()) &&
           verifier.EndTable();
  }
};

struct FeatureBatchBuilder {
  typedef FeatureBatch Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_eintraege(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nakama::v3::QuellenEintrag>>> eintraege) {
    fbb_.AddOffset(FeatureBatch::VT_EINTRAEGE, eintraege);
  }
  explicit FeatureBatchBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FeatureBatch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FeatureBatch>(end);
    fbb_.Required(o, FeatureBatch::VT_EINTRAEGE);
    return o;
  }
};

inline ::flatbuffers::Offset<FeatureBatch> CreateFeatureBatch(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<nakama::v3::QuellenEintrag>>> eintraege = 0) {
  FeatureBatchBuilder builder_(_fbb);
  builder_.add_eintraege(eintraege);
  return builder_.Finish();
}

struct FeatureBatch::Traits {
  using type = FeatureBatch;
  static auto constexpr Create = CreateFeatureBatch;
};

inline ::flatbuffers::Offset<FeatureBatch> CreateFeatureBatchDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<nakama::v3::QuellenEintrag>> *eintraege = nullptr) {
  auto eintraege__ = eintraege ? _fbb.CreateVector<::flatbuffers::Offset<nakama::v3::QuellenEintrag>>(*eintraege) : 0;
  return nakama::v3::CreateFeatureBatch(
      _fbb,
      eintraege__);
}

inline const nakama::v3::FeatureBatch *GetFeatureBatch(const void *buf) {
  return ::flatbuffers::GetRoot<nakama::v3::FeatureBatch>(buf);
}

inline const nakama::v3::FeatureBatch *GetSizePrefixedFeatureBatch(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<nakama::v3::FeatureBatch>(buf);
}

inline const char *FeatureBatchIdentifier() {
  return "NKT3";
}

inline bool FeatureBatchBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, FeatureBatchIdentifier());
}

inline bool SizePrefixedFeatureBatchBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, FeatureBatchIdentifier(), true);
}

template <bool B = false>
inline bool VerifyFeatureBatchBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<nakama::v3::FeatureBatch>(FeatureBatchIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedFeatureBatchBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<nakama::v3::FeatureBatch>(FeatureBatchIdentifier());
}

inline const char *FeatureBatchExtension() {
  return "nktb";
}

inline void FinishFeatureBatchBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<nakama::v3::FeatureBatch> root) {
  fbb.Finish(root, FeatureBatchIdentifier());
}

inline void FinishSizePrefixedFeatureBatchBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<nakama::v3::FeatureBatch> root) {
  fbb.FinishSizePrefixed(root, FeatureBatchIdentifier());
}

}  // namespace v3
}  // namespace nakama

#endif  // FLATBUFFERS_GENERATED_NAKAMATELEMETRYV1_NAKAMA_V3_H_
