// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod nakama {

#[allow(unused_imports, dead_code)]
pub mod v_3 {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_BANDGITTER: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_BANDGITTER: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_BANDGITTER: [Bandgitter; 3] = [
  Bandgitter::unbekannt,
  Bandgitter::nakama_1_24_oct_30_18k_v1,
  Bandgitter::nakama_log64_v1,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Bandgitter(pub u8);
#[allow(non_upper_case_globals)]
impl Bandgitter {
  pub const unbekannt: Self = Self(0);
  pub const nakama_1_24_oct_30_18k_v1: Self = Self(1);
  pub const nakama_log64_v1: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::unbekannt,
    Self::nakama_1_24_oct_30_18k_v1,
    Self::nakama_log64_v1,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::unbekannt => Some("unbekannt"),
      Self::nakama_1_24_oct_30_18k_v1 => Some("nakama_1_24_oct_30_18k_v1"),
      Self::nakama_log64_v1 => Some("nakama_log64_v1"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Bandgitter {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Bandgitter {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Bandgitter {
    type Output = Bandgitter;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Bandgitter {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Bandgitter {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Bandgitter {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_BAND_ENCODING: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_BAND_ENCODING: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_BAND_ENCODING: [BandEncoding; 4] = [
  BandEncoding::unbekannt,
  BandEncoding::q_db_0p1_i16,
  BandEncoding::q_db_0p01_i16,
  BandEncoding::float32,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct BandEncoding(pub u8);
#[allow(non_upper_case_globals)]
impl BandEncoding {
  pub const unbekannt: Self = Self(0);
  pub const q_db_0p1_i16: Self = Self(1);
  pub const q_db_0p01_i16: Self = Self(2);
  pub const float32: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::unbekannt,
    Self::q_db_0p1_i16,
    Self::q_db_0p01_i16,
    Self::float32,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::unbekannt => Some("unbekannt"),
      Self::q_db_0p1_i16 => Some("q_db_0p1_i16"),
      Self::q_db_0p01_i16 => Some("q_db_0p01_i16"),
      Self::float32 => Some("float32"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for BandEncoding {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for BandEncoding {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for BandEncoding {
    type Output = BandEncoding;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for BandEncoding {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for BandEncoding {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for BandEncoding {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ZEITBASIS: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ZEITBASIS: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ZEITBASIS: [Zeitbasis; 3] = [
  Zeitbasis::unbekannt,
  Zeitbasis::project_samples,
  Zeitbasis::local_monotonic,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Zeitbasis(pub u8);
#[allow(non_upper_case_globals)]
impl Zeitbasis {
  pub const unbekannt: Self = Self(0);
  pub const project_samples: Self = Self(1);
  pub const local_monotonic: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::unbekannt,
    Self::project_samples,
    Self::local_monotonic,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::unbekannt => Some("unbekannt"),
      Self::project_samples => Some("project_samples"),
      Self::local_monotonic => Some("local_monotonic"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Zeitbasis {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Zeitbasis {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Zeitbasis {
    type Output = Zeitbasis;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Zeitbasis {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Zeitbasis {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Zeitbasis {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_HERLEITUNG: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_HERLEITUNG: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_HERLEITUNG: [Herleitung; 3] = [
  Herleitung::unbekannt,
  Herleitung::validated_block_mapping,
  Herleitung::unproven,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Herleitung(pub u8);
#[allow(non_upper_case_globals)]
impl Herleitung {
  pub const unbekannt: Self = Self(0);
  pub const validated_block_mapping: Self = Self(1);
  pub const unproven: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::unbekannt,
    Self::validated_block_mapping,
    Self::unproven,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::unbekannt => Some("unbekannt"),
      Self::validated_block_mapping => Some("validated_block_mapping"),
      Self::unproven => Some("unproven"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Herleitung {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Herleitung {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Herleitung {
    type Output = Herleitung;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Herleitung {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Herleitung {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Herleitung {}
#[allow(non_upper_case_globals)]
mod bitflags_gueltigkeit {
  ::flatbuffers::bitflags::bitflags! {
    #[derive(Default, Debug, Clone, Copy, PartialEq)]
    pub struct Gueltigkeit: u8 {
      const project_time = 1;
      const play_state = 2;
      const record_state = 4;
      const cycle_bounds = 8;
      const continuous_time = 16;
      const input_presentation_latency = 32;
      const output_presentation_latency = 64;
    }
  }
}
pub use self::bitflags_gueltigkeit::Gueltigkeit;

impl<'a> ::flatbuffers::Follow<'a> for Gueltigkeit {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self::from_bits_retain(b)
  }
}

impl ::flatbuffers::Push for Gueltigkeit {
    type Output = Gueltigkeit;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.bits()) };
    }
}

impl ::flatbuffers::EndianScalar for Gueltigkeit {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.bits().to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self::from_bits_retain(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Gueltigkeit {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Gueltigkeit {}
pub enum AdresseOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Effektive Steueradresse (§32.1). KEIN Feld hier ist additiv: eine unbekannte
/// Eigenschaft waere eine unbekannte Zieladresse. Alle fuenf sind `required` —
/// das prueft schon der FlatBuffers-Verifier, nicht erst unser Leser.
/// Die vier Hex-Token sind je 32 Kleinbuchstaben-Hexziffern (Def. `hex32` des
/// JSON-Vertrags); die SID wird nie geparst, nur verglichen.
pub struct Adresse<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Adresse<'a> {
  type Inner = Adresse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Adresse<'a> {
  pub const VT_LOGON_SID: ::flatbuffers::VOffsetT = 4;
  pub const VT_PROJECT_BINDING_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_SESSION_EPOCH: ::flatbuffers::VOffsetT = 8;
  pub const VT_INSTANCE_ID: ::flatbuffers::VOffsetT = 10;
  pub const VT_RUNTIME_NONCE: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Adresse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AdresseArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Adresse<'bldr>> {
    let mut builder = AdresseBuilder::new(_fbb);
    if let Some(x) = args.runtime_nonce { builder.add_runtime_nonce(x); }
    if let Some(x) = args.instance_id { builder.add_instance_id(x); }
    if let Some(x) = args.session_epoch { builder.add_session_epoch(x); }
    if let Some(x) = args.project_binding_id { builder.add_project_binding_id(x); }
    if let Some(x) = args.logon_sid { builder.add_logon_sid(x); }
    builder.finish()
  }


  #[inline]
  pub fn logon_sid(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Adresse::VT_LOGON_SID, None).unwrap()}
  }
  #[inline]
  pub fn project_binding_id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Adresse::VT_PROJECT_BINDING_ID, None).unwrap()}
  }
  #[inline]
  pub fn session_epoch(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Adresse::VT_SESSION_EPOCH, None).unwrap()}
  }
  #[inline]
  pub fn instance_id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Adresse::VT_INSTANCE_ID, None).unwrap()}
  }
  #[inline]
  pub fn runtime_nonce(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Adresse::VT_RUNTIME_NONCE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Adresse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("logon_sid", Self::VT_LOGON_SID, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("project_binding_id", Self::VT_PROJECT_BINDING_ID, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("session_epoch", Self::VT_SESSION_EPOCH, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("instance_id", Self::VT_INSTANCE_ID, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("runtime_nonce", Self::VT_RUNTIME_NONCE, true)?
     .finish();
    Ok(())
  }
}
pub struct AdresseArgs<'a> {
    pub logon_sid: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub project_binding_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub session_epoch: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub instance_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub runtime_nonce: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for AdresseArgs<'a> {
  #[inline]
  fn default() -> Self {
    AdresseArgs {
      logon_sid: None, // required field
      project_binding_id: None, // required field
      session_epoch: None, // required field
      instance_id: None, // required field
      runtime_nonce: None, // required field
    }
  }
}

pub struct AdresseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AdresseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_logon_sid(&mut self, logon_sid: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Adresse::VT_LOGON_SID, logon_sid);
  }
  #[inline]
  pub fn add_project_binding_id(&mut self, project_binding_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Adresse::VT_PROJECT_BINDING_ID, project_binding_id);
  }
  #[inline]
  pub fn add_session_epoch(&mut self, session_epoch: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Adresse::VT_SESSION_EPOCH, session_epoch);
  }
  #[inline]
  pub fn add_instance_id(&mut self, instance_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Adresse::VT_INSTANCE_ID, instance_id);
  }
  #[inline]
  pub fn add_runtime_nonce(&mut self, runtime_nonce: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Adresse::VT_RUNTIME_NONCE, runtime_nonce);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AdresseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AdresseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Adresse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Adresse::VT_LOGON_SID,"logon_sid");
    self.fbb_.required(o, Adresse::VT_PROJECT_BINDING_ID,"project_binding_id");
    self.fbb_.required(o, Adresse::VT_SESSION_EPOCH,"session_epoch");
    self.fbb_.required(o, Adresse::VT_INSTANCE_ID,"instance_id");
    self.fbb_.required(o, Adresse::VT_RUNTIME_NONCE,"runtime_nonce");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Adresse<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Adresse");
      ds.field("logon_sid", &self.logon_sid());
      ds.field("project_binding_id", &self.project_binding_id());
      ds.field("session_epoch", &self.session_epoch());
      ds.field("instance_id", &self.instance_id());
      ds.field("runtime_nonce", &self.runtime_nonce());
      ds.finish()
  }
}
pub enum AbgeleiteteGrenzenOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Abgeleitete Samplegrenzen einer Schleife. NUR gueltig, wenn PPQ, Projektzeit
/// und Tempo im Block eine durch FL-Goldens validierte Abbildung erlauben
/// (§32.3) — deshalb traegt das Objekt seine Herleitung mit, statt sie dem
/// Empfaenger zu ueberlassen.
pub struct AbgeleiteteGrenzen<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for AbgeleiteteGrenzen<'a> {
  type Inner = AbgeleiteteGrenzen<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> AbgeleiteteGrenzen<'a> {
  pub const VT_START: ::flatbuffers::VOffsetT = 4;
  pub const VT_ENDE: ::flatbuffers::VOffsetT = 6;
  pub const VT_HERLEITUNG: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    AbgeleiteteGrenzen { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AbgeleiteteGrenzenArgs
  ) -> ::flatbuffers::WIPOffset<AbgeleiteteGrenzen<'bldr>> {
    let mut builder = AbgeleiteteGrenzenBuilder::new(_fbb);
    builder.add_ende(args.ende);
    builder.add_start(args.start);
    builder.add_herleitung(args.herleitung);
    builder.finish()
  }


  #[inline]
  pub fn start(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(AbgeleiteteGrenzen::VT_START, Some(0)).unwrap()}
  }
  #[inline]
  pub fn ende(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(AbgeleiteteGrenzen::VT_ENDE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn herleitung(&self) -> Herleitung {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Herleitung>(AbgeleiteteGrenzen::VT_HERLEITUNG, Some(Herleitung::unbekannt)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for AbgeleiteteGrenzen<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<i64>("start", Self::VT_START, false)?
     .visit_field::<i64>("ende", Self::VT_ENDE, false)?
     .visit_field::<Herleitung>("herleitung", Self::VT_HERLEITUNG, false)?
     .finish();
    Ok(())
  }
}
pub struct AbgeleiteteGrenzenArgs {
    pub start: i64,
    pub ende: i64,
    pub herleitung: Herleitung,
}
impl<'a> Default for AbgeleiteteGrenzenArgs {
  #[inline]
  fn default() -> Self {
    AbgeleiteteGrenzenArgs {
      start: 0,
      ende: 0,
      herleitung: Herleitung::unbekannt,
    }
  }
}

pub struct AbgeleiteteGrenzenBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AbgeleiteteGrenzenBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_start(&mut self, start: i64) {
    self.fbb_.push_slot::<i64>(AbgeleiteteGrenzen::VT_START, start, 0);
  }
  #[inline]
  pub fn add_ende(&mut self, ende: i64) {
    self.fbb_.push_slot::<i64>(AbgeleiteteGrenzen::VT_ENDE, ende, 0);
  }
  #[inline]
  pub fn add_herleitung(&mut self, herleitung: Herleitung) {
    self.fbb_.push_slot::<Herleitung>(AbgeleiteteGrenzen::VT_HERLEITUNG, herleitung, Herleitung::unbekannt);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AbgeleiteteGrenzenBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AbgeleiteteGrenzenBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<AbgeleiteteGrenzen<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for AbgeleiteteGrenzen<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("AbgeleiteteGrenzen");
      ds.field("start", &self.start());
      ds.field("ende", &self.ende());
      ds.field("herleitung", &self.herleitung());
      ds.finish()
  }
}
pub enum SchleifeOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Schleifengrenzen. VST3 liefert sie als PPQ; Samplegrenzen sind ABGELEITET.
/// `active` und `bounds_valid` sind bool ohne Optionalitaet: ihr Default false
/// ist die richtige Bedeutung eines fehlenden Feldes (§32.3).
pub struct Schleife<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Schleife<'a> {
  type Inner = Schleife<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Schleife<'a> {
  pub const VT_ACTIVE: ::flatbuffers::VOffsetT = 4;
  pub const VT_BOUNDS_VALID: ::flatbuffers::VOffsetT = 6;
  pub const VT_START_PPQ: ::flatbuffers::VOffsetT = 8;
  pub const VT_END_PPQ: ::flatbuffers::VOffsetT = 10;
  pub const VT_ABGELEITETE_GRENZEN: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Schleife { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SchleifeArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Schleife<'bldr>> {
    let mut builder = SchleifeBuilder::new(_fbb);
    if let Some(x) = args.end_ppq { builder.add_end_ppq(x); }
    if let Some(x) = args.start_ppq { builder.add_start_ppq(x); }
    if let Some(x) = args.abgeleitete_grenzen { builder.add_abgeleitete_grenzen(x); }
    builder.add_bounds_valid(args.bounds_valid);
    builder.add_active(args.active);
    builder.finish()
  }


  #[inline]
  pub fn active(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Schleife::VT_ACTIVE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn bounds_valid(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Schleife::VT_BOUNDS_VALID, Some(false)).unwrap()}
  }
  #[inline]
  pub fn start_ppq(&self) -> Option<f64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(Schleife::VT_START_PPQ, None)}
  }
  #[inline]
  pub fn end_ppq(&self) -> Option<f64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(Schleife::VT_END_PPQ, None)}
  }
  #[inline]
  pub fn abgeleitete_grenzen(&self) -> Option<AbgeleiteteGrenzen<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<AbgeleiteteGrenzen>>(Schleife::VT_ABGELEITETE_GRENZEN, None)}
  }
}

impl ::flatbuffers::Verifiable for Schleife<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<bool>("active", Self::VT_ACTIVE, false)?
     .visit_field::<bool>("bounds_valid", Self::VT_BOUNDS_VALID, false)?
     .visit_field::<f64>("start_ppq", Self::VT_START_PPQ, false)?
     .visit_field::<f64>("end_ppq", Self::VT_END_PPQ, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<AbgeleiteteGrenzen>>("abgeleitete_grenzen", Self::VT_ABGELEITETE_GRENZEN, false)?
     .finish();
    Ok(())
  }
}
pub struct SchleifeArgs<'a> {
    pub active: bool,
    pub bounds_valid: bool,
    pub start_ppq: Option<f64>,
    pub end_ppq: Option<f64>,
    pub abgeleitete_grenzen: Option<::flatbuffers::WIPOffset<AbgeleiteteGrenzen<'a>>>,
}
impl<'a> Default for SchleifeArgs<'a> {
  #[inline]
  fn default() -> Self {
    SchleifeArgs {
      active: false,
      bounds_valid: false,
      start_ppq: None,
      end_ppq: None,
      abgeleitete_grenzen: None,
    }
  }
}

pub struct SchleifeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SchleifeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_active(&mut self, active: bool) {
    self.fbb_.push_slot::<bool>(Schleife::VT_ACTIVE, active, false);
  }
  #[inline]
  pub fn add_bounds_valid(&mut self, bounds_valid: bool) {
    self.fbb_.push_slot::<bool>(Schleife::VT_BOUNDS_VALID, bounds_valid, false);
  }
  #[inline]
  pub fn add_start_ppq(&mut self, start_ppq: f64) {
    self.fbb_.push_slot_always::<f64>(Schleife::VT_START_PPQ, start_ppq);
  }
  #[inline]
  pub fn add_end_ppq(&mut self, end_ppq: f64) {
    self.fbb_.push_slot_always::<f64>(Schleife::VT_END_PPQ, end_ppq);
  }
  #[inline]
  pub fn add_abgeleitete_grenzen(&mut self, abgeleitete_grenzen: ::flatbuffers::WIPOffset<AbgeleiteteGrenzen<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<AbgeleiteteGrenzen>>(Schleife::VT_ABGELEITETE_GRENZEN, abgeleitete_grenzen);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SchleifeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SchleifeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Schleife<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Schleife<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Schleife");
      ds.field("active", &self.active());
      ds.field("bounds_valid", &self.bounds_valid());
      ds.field("start_ppq", &self.start_ppq());
      ds.field("end_ppq", &self.end_ppq());
      ds.field("abgeleitete_grenzen", &self.abgeleitete_grenzen());
      ds.finish()
  }
}
pub enum TransportstempelOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Zeitbasis und explizite Gueltigkeit jedes zeitabhaengigen Frames (§32.3).
///
/// Die drei `= null`-Felder sind echte FlatBuffers-Optionals: bei ihnen ist
/// "nicht gemeldet" von "gemeldet als 0" unterscheidbar. Bei
/// `project_sample_start` ist das keine Feinheit — 0 ist eine voellig normale
/// Projektposition, und ein Default 0 haette den Frameanfang stillschweigend
/// an den Songanfang gelegt.
pub struct Transportstempel<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Transportstempel<'a> {
  type Inner = Transportstempel<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Transportstempel<'a> {
  pub const VT_TRANSPORT_EPOCH: ::flatbuffers::VOffsetT = 4;
  pub const VT_CONTINUITY_SEGMENT: ::flatbuffers::VOffsetT = 6;
  pub const VT_SEQUENCE: ::flatbuffers::VOffsetT = 8;
  pub const VT_ZEITBASIS: ::flatbuffers::VOffsetT = 10;
  pub const VT_PROJECT_SAMPLE_START: ::flatbuffers::VOffsetT = 12;
  pub const VT_SAMPLE_COUNT: ::flatbuffers::VOffsetT = 14;
  pub const VT_SAMPLE_RATE: ::flatbuffers::VOffsetT = 16;
  pub const VT_PLAYING: ::flatbuffers::VOffsetT = 18;
  pub const VT_RECORDING: ::flatbuffers::VOffsetT = 20;
  pub const VT_CONTINUOUS_TIME_SAMPLES: ::flatbuffers::VOffsetT = 22;
  pub const VT_SCHLEIFE: ::flatbuffers::VOffsetT = 24;
  pub const VT_INPUT_PRESENTATION_LATENCY: ::flatbuffers::VOffsetT = 26;
  pub const VT_OUTPUT_PRESENTATION_LATENCY: ::flatbuffers::VOffsetT = 28;
  pub const VT_GUELTIGKEIT: ::flatbuffers::VOffsetT = 30;
  pub const VT_PROCESS_CONTEXT_PRESENT: ::flatbuffers::VOffsetT = 32;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Transportstempel { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TransportstempelArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Transportstempel<'bldr>> {
    let mut builder = TransportstempelBuilder::new(_fbb);
    if let Some(x) = args.continuous_time_samples { builder.add_continuous_time_samples(x); }
    builder.add_sample_rate(args.sample_rate);
    if let Some(x) = args.project_sample_start { builder.add_project_sample_start(x); }
    builder.add_sequence(args.sequence);
    builder.add_continuity_segment(args.continuity_segment);
    builder.add_transport_epoch(args.transport_epoch);
    if let Some(x) = args.output_presentation_latency { builder.add_output_presentation_latency(x); }
    if let Some(x) = args.input_presentation_latency { builder.add_input_presentation_latency(x); }
    if let Some(x) = args.schleife { builder.add_schleife(x); }
    builder.add_sample_count(args.sample_count);
    if let Some(x) = args.process_context_present { builder.add_process_context_present(x); }
    builder.add_gueltigkeit(args.gueltigkeit);
    builder.add_recording(args.recording);
    builder.add_playing(args.playing);
    builder.add_zeitbasis(args.zeitbasis);
    builder.finish()
  }


  #[inline]
  pub fn transport_epoch(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Transportstempel::VT_TRANSPORT_EPOCH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn continuity_segment(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Transportstempel::VT_CONTINUITY_SEGMENT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn sequence(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Transportstempel::VT_SEQUENCE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn zeitbasis(&self) -> Zeitbasis {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Zeitbasis>(Transportstempel::VT_ZEITBASIS, Some(Zeitbasis::unbekannt)).unwrap()}
  }
  #[inline]
  pub fn project_sample_start(&self) -> Option<i64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Transportstempel::VT_PROJECT_SAMPLE_START, None)}
  }
  #[inline]
  pub fn sample_count(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Transportstempel::VT_SAMPLE_COUNT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn sample_rate(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(Transportstempel::VT_SAMPLE_RATE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn playing(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Transportstempel::VT_PLAYING, Some(false)).unwrap()}
  }
  #[inline]
  pub fn recording(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Transportstempel::VT_RECORDING, Some(false)).unwrap()}
  }
  #[inline]
  pub fn continuous_time_samples(&self) -> Option<i64> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Transportstempel::VT_CONTINUOUS_TIME_SAMPLES, None)}
  }
  #[inline]
  pub fn schleife(&self) -> Option<Schleife<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Schleife>>(Transportstempel::VT_SCHLEIFE, None)}
  }
  #[inline]
  pub fn input_presentation_latency(&self) -> Option<u32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Transportstempel::VT_INPUT_PRESENTATION_LATENCY, None)}
  }
  #[inline]
  pub fn output_presentation_latency(&self) -> Option<u32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Transportstempel::VT_OUTPUT_PRESENTATION_LATENCY, None)}
  }
  #[inline]
  pub fn gueltigkeit(&self) -> Gueltigkeit {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Gueltigkeit>(Transportstempel::VT_GUELTIGKEIT, Some(Default::default())).unwrap()}
  }
  /// §32.3 woertlich: "Die Wrapper-Bridge liefert deshalb
  /// process_context_present und unabhaengige Validity-Bits; ohne Bridge gilt
  /// Projektzeit als unbewiesen."
  ///
  /// OPTIONAL und nicht `bool` mit Default false: ein Default machte "der
  /// Sender hat das Feld weggelassen" ununterscheidbar von "der Host hat
  /// keinen Context angelegt". Der Leser verlangt es. Und es ist bewusst KEIN
  /// Gueltigkeitsbit - es beschreibt nicht die Gueltigkeit EINES Feldes,
  /// sondern ob der Host ueberhaupt eine Zeitquelle bereitgestellt hat.
  #[inline]
  pub fn process_context_present(&self) -> Option<bool> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Transportstempel::VT_PROCESS_CONTEXT_PRESENT, None)}
  }
}

impl ::flatbuffers::Verifiable for Transportstempel<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("transport_epoch", Self::VT_TRANSPORT_EPOCH, false)?
     .visit_field::<u64>("continuity_segment", Self::VT_CONTINUITY_SEGMENT, false)?
     .visit_field::<u64>("sequence", Self::VT_SEQUENCE, false)?
     .visit_field::<Zeitbasis>("zeitbasis", Self::VT_ZEITBASIS, false)?
     .visit_field::<i64>("project_sample_start", Self::VT_PROJECT_SAMPLE_START, false)?
     .visit_field::<u32>("sample_count", Self::VT_SAMPLE_COUNT, false)?
     .visit_field::<f64>("sample_rate", Self::VT_SAMPLE_RATE, false)?
     .visit_field::<bool>("playing", Self::VT_PLAYING, false)?
     .visit_field::<bool>("recording", Self::VT_RECORDING, false)?
     .visit_field::<i64>("continuous_time_samples", Self::VT_CONTINUOUS_TIME_SAMPLES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Schleife>>("schleife", Self::VT_SCHLEIFE, false)?
     .visit_field::<u32>("input_presentation_latency", Self::VT_INPUT_PRESENTATION_LATENCY, false)?
     .visit_field::<u32>("output_presentation_latency", Self::VT_OUTPUT_PRESENTATION_LATENCY, false)?
     .visit_field::<Gueltigkeit>("gueltigkeit", Self::VT_GUELTIGKEIT, false)?
     .visit_field::<bool>("process_context_present", Self::VT_PROCESS_CONTEXT_PRESENT, false)?
     .finish();
    Ok(())
  }
}
pub struct TransportstempelArgs<'a> {
    pub transport_epoch: u64,
    pub continuity_segment: u64,
    pub sequence: u64,
    pub zeitbasis: Zeitbasis,
    pub project_sample_start: Option<i64>,
    pub sample_count: u32,
    pub sample_rate: f64,
    pub playing: bool,
    pub recording: bool,
    pub continuous_time_samples: Option<i64>,
    pub schleife: Option<::flatbuffers::WIPOffset<Schleife<'a>>>,
    pub input_presentation_latency: Option<u32>,
    pub output_presentation_latency: Option<u32>,
    pub gueltigkeit: Gueltigkeit,
    pub process_context_present: Option<bool>,
}
impl<'a> Default for TransportstempelArgs<'a> {
  #[inline]
  fn default() -> Self {
    TransportstempelArgs {
      transport_epoch: 0,
      continuity_segment: 0,
      sequence: 0,
      zeitbasis: Zeitbasis::unbekannt,
      project_sample_start: None,
      sample_count: 0,
      sample_rate: 0.0,
      playing: false,
      recording: false,
      continuous_time_samples: None,
      schleife: None,
      input_presentation_latency: None,
      output_presentation_latency: None,
      gueltigkeit: Default::default(),
      process_context_present: None,
    }
  }
}

pub struct TransportstempelBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TransportstempelBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_transport_epoch(&mut self, transport_epoch: u64) {
    self.fbb_.push_slot::<u64>(Transportstempel::VT_TRANSPORT_EPOCH, transport_epoch, 0);
  }
  #[inline]
  pub fn add_continuity_segment(&mut self, continuity_segment: u64) {
    self.fbb_.push_slot::<u64>(Transportstempel::VT_CONTINUITY_SEGMENT, continuity_segment, 0);
  }
  #[inline]
  pub fn add_sequence(&mut self, sequence: u64) {
    self.fbb_.push_slot::<u64>(Transportstempel::VT_SEQUENCE, sequence, 0);
  }
  #[inline]
  pub fn add_zeitbasis(&mut self, zeitbasis: Zeitbasis) {
    self.fbb_.push_slot::<Zeitbasis>(Transportstempel::VT_ZEITBASIS, zeitbasis, Zeitbasis::unbekannt);
  }
  #[inline]
  pub fn add_project_sample_start(&mut self, project_sample_start: i64) {
    self.fbb_.push_slot_always::<i64>(Transportstempel::VT_PROJECT_SAMPLE_START, project_sample_start);
  }
  #[inline]
  pub fn add_sample_count(&mut self, sample_count: u32) {
    self.fbb_.push_slot::<u32>(Transportstempel::VT_SAMPLE_COUNT, sample_count, 0);
  }
  #[inline]
  pub fn add_sample_rate(&mut self, sample_rate: f64) {
    self.fbb_.push_slot::<f64>(Transportstempel::VT_SAMPLE_RATE, sample_rate, 0.0);
  }
  #[inline]
  pub fn add_playing(&mut self, playing: bool) {
    self.fbb_.push_slot::<bool>(Transportstempel::VT_PLAYING, playing, false);
  }
  #[inline]
  pub fn add_recording(&mut self, recording: bool) {
    self.fbb_.push_slot::<bool>(Transportstempel::VT_RECORDING, recording, false);
  }
  #[inline]
  pub fn add_continuous_time_samples(&mut self, continuous_time_samples: i64) {
    self.fbb_.push_slot_always::<i64>(Transportstempel::VT_CONTINUOUS_TIME_SAMPLES, continuous_time_samples);
  }
  #[inline]
  pub fn add_schleife(&mut self, schleife: ::flatbuffers::WIPOffset<Schleife<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Schleife>>(Transportstempel::VT_SCHLEIFE, schleife);
  }
  #[inline]
  pub fn add_input_presentation_latency(&mut self, input_presentation_latency: u32) {
    self.fbb_.push_slot_always::<u32>(Transportstempel::VT_INPUT_PRESENTATION_LATENCY, input_presentation_latency);
  }
  #[inline]
  pub fn add_output_presentation_latency(&mut self, output_presentation_latency: u32) {
    self.fbb_.push_slot_always::<u32>(Transportstempel::VT_OUTPUT_PRESENTATION_LATENCY, output_presentation_latency);
  }
  #[inline]
  pub fn add_gueltigkeit(&mut self, gueltigkeit: Gueltigkeit) {
    self.fbb_.push_slot::<Gueltigkeit>(Transportstempel::VT_GUELTIGKEIT, gueltigkeit, Default::default());
  }
  #[inline]
  pub fn add_process_context_present(&mut self, process_context_present: bool) {
    self.fbb_.push_slot_always::<bool>(Transportstempel::VT_PROCESS_CONTEXT_PRESENT, process_context_present);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TransportstempelBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TransportstempelBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Transportstempel<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Transportstempel<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Transportstempel");
      ds.field("transport_epoch", &self.transport_epoch());
      ds.field("continuity_segment", &self.continuity_segment());
      ds.field("sequence", &self.sequence());
      ds.field("zeitbasis", &self.zeitbasis());
      ds.field("project_sample_start", &self.project_sample_start());
      ds.field("sample_count", &self.sample_count());
      ds.field("sample_rate", &self.sample_rate());
      ds.field("playing", &self.playing());
      ds.field("recording", &self.recording());
      ds.field("continuous_time_samples", &self.continuous_time_samples());
      ds.field("schleife", &self.schleife());
      ds.field("input_presentation_latency", &self.input_presentation_latency());
      ds.field("output_presentation_latency", &self.output_presentation_latency());
      ds.field("gueltigkeit", &self.gueltigkeit());
      ds.field("process_context_present", &self.process_context_present());
      ds.finish()
  }
}
pub enum BandwerteOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Ein Bandsatz mit seinem Gitter, seiner Kodierung, seiner Gueltigkeitsbitmap
/// und seinem Saettigungsbit (§33.1). Gegenstueck zu `$defs/bandwerte` im
/// JSON-Vertrag; Skalierung und Rundung stehen in quantisierung-v1.json.
///
/// Die Kodierung steht IM Batch und wird nie aus dem Nachrichtentyp geraten
/// (§33.1 woertlich). Genau zwei Traeger existieren: `werte_i16` fuer beide
/// q_db-Kodierungen, `werte_f32` fuer float32. Der Leser erzwingt, dass genau
/// EINER gesetzt ist und dass er zur Kodierung passt — ein Puffer mit
/// encoding=float32 und gesetztem `werte_i16` ist ungueltig, nicht "irgendwie
/// interpretierbar".
///
/// `gueltig_bitmap` ist LSB-first ueber ceil(n/8) Bytes: Band i sitzt in Byte
/// i/8, Bit i%8. Die Fuellbits des letzten Bytes MUESSEN 0 sein — sonst
/// erzeugen zwei Sender fuer denselben Messwert zwei verschiedene Puffer, und
/// ein Bytevergleich waere keine Aussage mehr.
pub struct Bandwerte<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Bandwerte<'a> {
  type Inner = Bandwerte<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Bandwerte<'a> {
  pub const VT_GITTER: ::flatbuffers::VOffsetT = 4;
  pub const VT_ENCODING: ::flatbuffers::VOffsetT = 6;
  pub const VT_WERTE_I16: ::flatbuffers::VOffsetT = 8;
  pub const VT_WERTE_F32: ::flatbuffers::VOffsetT = 10;
  pub const VT_GUELTIG_BITMAP: ::flatbuffers::VOffsetT = 12;
  pub const VT_SATURATED: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Bandwerte { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BandwerteArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Bandwerte<'bldr>> {
    let mut builder = BandwerteBuilder::new(_fbb);
    if let Some(x) = args.gueltig_bitmap { builder.add_gueltig_bitmap(x); }
    if let Some(x) = args.werte_f32 { builder.add_werte_f32(x); }
    if let Some(x) = args.werte_i16 { builder.add_werte_i16(x); }
    builder.add_saturated(args.saturated);
    builder.add_encoding(args.encoding);
    builder.add_gitter(args.gitter);
    builder.finish()
  }


  #[inline]
  pub fn gitter(&self) -> Bandgitter {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Bandgitter>(Bandwerte::VT_GITTER, Some(Bandgitter::unbekannt)).unwrap()}
  }
  #[inline]
  pub fn encoding(&self) -> BandEncoding {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<BandEncoding>(Bandwerte::VT_ENCODING, Some(BandEncoding::unbekannt)).unwrap()}
  }
  #[inline]
  pub fn werte_i16(&self) -> Option<::flatbuffers::Vector<'a, i16>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, i16>>>(Bandwerte::VT_WERTE_I16, None)}
  }
  #[inline]
  pub fn werte_f32(&self) -> Option<::flatbuffers::Vector<'a, f32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, f32>>>(Bandwerte::VT_WERTE_F32, None)}
  }
  #[inline]
  pub fn gueltig_bitmap(&self) -> ::flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(Bandwerte::VT_GUELTIG_BITMAP, None).unwrap()}
  }
  #[inline]
  pub fn saturated(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Bandwerte::VT_SATURATED, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Bandwerte<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<Bandgitter>("gitter", Self::VT_GITTER, false)?
     .visit_field::<BandEncoding>("encoding", Self::VT_ENCODING, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, i16>>>("werte_i16", Self::VT_WERTE_I16, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, f32>>>("werte_f32", Self::VT_WERTE_F32, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("gueltig_bitmap", Self::VT_GUELTIG_BITMAP, true)?
     .visit_field::<bool>("saturated", Self::VT_SATURATED, false)?
     .finish();
    Ok(())
  }
}
pub struct BandwerteArgs<'a> {
    pub gitter: Bandgitter,
    pub encoding: BandEncoding,
    pub werte_i16: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, i16>>>,
    pub werte_f32: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, f32>>>,
    pub gueltig_bitmap: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub saturated: bool,
}
impl<'a> Default for BandwerteArgs<'a> {
  #[inline]
  fn default() -> Self {
    BandwerteArgs {
      gitter: Bandgitter::unbekannt,
      encoding: BandEncoding::unbekannt,
      werte_i16: None,
      werte_f32: None,
      gueltig_bitmap: None, // required field
      saturated: false,
    }
  }
}

pub struct BandwerteBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> BandwerteBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_gitter(&mut self, gitter: Bandgitter) {
    self.fbb_.push_slot::<Bandgitter>(Bandwerte::VT_GITTER, gitter, Bandgitter::unbekannt);
  }
  #[inline]
  pub fn add_encoding(&mut self, encoding: BandEncoding) {
    self.fbb_.push_slot::<BandEncoding>(Bandwerte::VT_ENCODING, encoding, BandEncoding::unbekannt);
  }
  #[inline]
  pub fn add_werte_i16(&mut self, werte_i16: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , i16>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Bandwerte::VT_WERTE_I16, werte_i16);
  }
  #[inline]
  pub fn add_werte_f32(&mut self, werte_f32: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , f32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Bandwerte::VT_WERTE_F32, werte_f32);
  }
  #[inline]
  pub fn add_gueltig_bitmap(&mut self, gueltig_bitmap: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Bandwerte::VT_GUELTIG_BITMAP, gueltig_bitmap);
  }
  #[inline]
  pub fn add_saturated(&mut self, saturated: bool) {
    self.fbb_.push_slot::<bool>(Bandwerte::VT_SATURATED, saturated, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> BandwerteBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BandwerteBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Bandwerte<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Bandwerte::VT_GUELTIG_BITMAP,"gueltig_bitmap");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Bandwerte<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Bandwerte");
      ds.field("gitter", &self.gitter());
      ds.field("encoding", &self.encoding());
      ds.field("werte_i16", &self.werte_i16());
      ds.field("werte_f32", &self.werte_f32());
      ds.field("gueltig_bitmap", &self.gueltig_bitmap());
      ds.field("saturated", &self.saturated());
      ds.finish()
  }
}
pub enum FrameOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Ein Messframe EINER Quelle (§33.2, Live-Telemetrie 10 Hz).
///
/// Alle Kennzahlen sind Optionals. Das ist die NaN-Ehrlichkeit dieses Projekts
/// im Binaerformat: ein nicht messbarer Wert wird WEGGELASSEN, nicht als 0 oder
/// als NaN gesendet. Ein NaN oder ±inf auf der Leitung ist deshalb ein
/// Senderfehler und wird von beiden Beinen abgelehnt statt sanitisiert —
/// quantisierung-v1.json legt fest, dass Nichtendliches beim ERZEUGEN in
/// Wert 0 mit gueltig=false uebersetzt wird.
pub struct Frame<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Frame<'a> {
  type Inner = Frame<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Frame<'a> {
  pub const VT_TRANSPORT: ::flatbuffers::VOffsetT = 4;
  pub const VT_BAENDER: ::flatbuffers::VOffsetT = 6;
  pub const VT_METRICS_VERSION: ::flatbuffers::VOffsetT = 8;
  pub const VT_AKTIVITAET: ::flatbuffers::VOffsetT = 10;
  pub const VT_LUFS_S: ::flatbuffers::VOffsetT = 12;
  pub const VT_PEAK_DB: ::flatbuffers::VOffsetT = 14;
  pub const VT_CREST_DB: ::flatbuffers::VOffsetT = 16;
  pub const VT_PSR_DB: ::flatbuffers::VOffsetT = 18;
  pub const VT_BREITE: ::flatbuffers::VOffsetT = 20;
  pub const VT_KORRELATION: ::flatbuffers::VOffsetT = 22;
  pub const VT_BAND_STEREO: ::flatbuffers::VOffsetT = 24;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Frame { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FrameArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Frame<'bldr>> {
    let mut builder = FrameBuilder::new(_fbb);
    if let Some(x) = args.band_stereo { builder.add_band_stereo(x); }
    if let Some(x) = args.korrelation { builder.add_korrelation(x); }
    if let Some(x) = args.breite { builder.add_breite(x); }
    if let Some(x) = args.psr_db { builder.add_psr_db(x); }
    if let Some(x) = args.crest_db { builder.add_crest_db(x); }
    if let Some(x) = args.peak_db { builder.add_peak_db(x); }
    if let Some(x) = args.lufs_s { builder.add_lufs_s(x); }
    if let Some(x) = args.aktivitaet { builder.add_aktivitaet(x); }
    builder.add_metrics_version(args.metrics_version);
    if let Some(x) = args.baender { builder.add_baender(x); }
    if let Some(x) = args.transport { builder.add_transport(x); }
    builder.finish()
  }


  #[inline]
  pub fn transport(&self) -> Transportstempel<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Transportstempel>>(Frame::VT_TRANSPORT, None).unwrap()}
  }
  #[inline]
  pub fn baender(&self) -> Bandwerte<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Bandwerte>>(Frame::VT_BAENDER, None).unwrap()}
  }
  #[inline]
  pub fn metrics_version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Frame::VT_METRICS_VERSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn aktivitaet(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Frame::VT_AKTIVITAET, None)}
  }
  #[inline]
  pub fn lufs_s(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Frame::VT_LUFS_S, None)}
  }
  #[inline]
  pub fn peak_db(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Frame::VT_PEAK_DB, None)}
  }
  #[inline]
  pub fn crest_db(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Frame::VT_CREST_DB, None)}
  }
  #[inline]
  pub fn psr_db(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Frame::VT_PSR_DB, None)}
  }
  #[inline]
  pub fn breite(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Frame::VT_BREITE, None)}
  }
  #[inline]
  pub fn korrelation(&self) -> Option<f32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(Frame::VT_KORRELATION, None)}
  }
  /// Optionale Band-Stereobreite auf dem festen 64er-Loggitter. Sie ist ein
  /// eigener Bandsatz, nie eine Umdeutung von `breite`: float32, 64 Werte,
  /// acht Bitmapbytes, gueltige Werte im Bereich [0, 1], saturated=false.
  #[inline]
  pub fn band_stereo(&self) -> Option<Bandwerte<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Bandwerte>>(Frame::VT_BAND_STEREO, None)}
  }
}

impl ::flatbuffers::Verifiable for Frame<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Transportstempel>>("transport", Self::VT_TRANSPORT, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Bandwerte>>("baender", Self::VT_BAENDER, true)?
     .visit_field::<u32>("metrics_version", Self::VT_METRICS_VERSION, false)?
     .visit_field::<f32>("aktivitaet", Self::VT_AKTIVITAET, false)?
     .visit_field::<f32>("lufs_s", Self::VT_LUFS_S, false)?
     .visit_field::<f32>("peak_db", Self::VT_PEAK_DB, false)?
     .visit_field::<f32>("crest_db", Self::VT_CREST_DB, false)?
     .visit_field::<f32>("psr_db", Self::VT_PSR_DB, false)?
     .visit_field::<f32>("breite", Self::VT_BREITE, false)?
     .visit_field::<f32>("korrelation", Self::VT_KORRELATION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Bandwerte>>("band_stereo", Self::VT_BAND_STEREO, false)?
     .finish();
    Ok(())
  }
}
pub struct FrameArgs<'a> {
    pub transport: Option<::flatbuffers::WIPOffset<Transportstempel<'a>>>,
    pub baender: Option<::flatbuffers::WIPOffset<Bandwerte<'a>>>,
    pub metrics_version: u32,
    pub aktivitaet: Option<f32>,
    pub lufs_s: Option<f32>,
    pub peak_db: Option<f32>,
    pub crest_db: Option<f32>,
    pub psr_db: Option<f32>,
    pub breite: Option<f32>,
    pub korrelation: Option<f32>,
    pub band_stereo: Option<::flatbuffers::WIPOffset<Bandwerte<'a>>>,
}
impl<'a> Default for FrameArgs<'a> {
  #[inline]
  fn default() -> Self {
    FrameArgs {
      transport: None, // required field
      baender: None, // required field
      metrics_version: 0,
      aktivitaet: None,
      lufs_s: None,
      peak_db: None,
      crest_db: None,
      psr_db: None,
      breite: None,
      korrelation: None,
      band_stereo: None,
    }
  }
}

pub struct FrameBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FrameBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_transport(&mut self, transport: ::flatbuffers::WIPOffset<Transportstempel<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Transportstempel>>(Frame::VT_TRANSPORT, transport);
  }
  #[inline]
  pub fn add_baender(&mut self, baender: ::flatbuffers::WIPOffset<Bandwerte<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Bandwerte>>(Frame::VT_BAENDER, baender);
  }
  #[inline]
  pub fn add_metrics_version(&mut self, metrics_version: u32) {
    self.fbb_.push_slot::<u32>(Frame::VT_METRICS_VERSION, metrics_version, 0);
  }
  #[inline]
  pub fn add_aktivitaet(&mut self, aktivitaet: f32) {
    self.fbb_.push_slot_always::<f32>(Frame::VT_AKTIVITAET, aktivitaet);
  }
  #[inline]
  pub fn add_lufs_s(&mut self, lufs_s: f32) {
    self.fbb_.push_slot_always::<f32>(Frame::VT_LUFS_S, lufs_s);
  }
  #[inline]
  pub fn add_peak_db(&mut self, peak_db: f32) {
    self.fbb_.push_slot_always::<f32>(Frame::VT_PEAK_DB, peak_db);
  }
  #[inline]
  pub fn add_crest_db(&mut self, crest_db: f32) {
    self.fbb_.push_slot_always::<f32>(Frame::VT_CREST_DB, crest_db);
  }
  #[inline]
  pub fn add_psr_db(&mut self, psr_db: f32) {
    self.fbb_.push_slot_always::<f32>(Frame::VT_PSR_DB, psr_db);
  }
  #[inline]
  pub fn add_breite(&mut self, breite: f32) {
    self.fbb_.push_slot_always::<f32>(Frame::VT_BREITE, breite);
  }
  #[inline]
  pub fn add_korrelation(&mut self, korrelation: f32) {
    self.fbb_.push_slot_always::<f32>(Frame::VT_KORRELATION, korrelation);
  }
  #[inline]
  pub fn add_band_stereo(&mut self, band_stereo: ::flatbuffers::WIPOffset<Bandwerte<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Bandwerte>>(Frame::VT_BAND_STEREO, band_stereo);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FrameBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FrameBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Frame<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Frame::VT_TRANSPORT,"transport");
    self.fbb_.required(o, Frame::VT_BAENDER,"baender");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Frame<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Frame");
      ds.field("transport", &self.transport());
      ds.field("baender", &self.baender());
      ds.field("metrics_version", &self.metrics_version());
      ds.field("aktivitaet", &self.aktivitaet());
      ds.field("lufs_s", &self.lufs_s());
      ds.field("peak_db", &self.peak_db());
      ds.field("crest_db", &self.crest_db());
      ds.field("psr_db", &self.psr_db());
      ds.field("breite", &self.breite());
      ds.field("korrelation", &self.korrelation());
      ds.field("band_stereo", &self.band_stereo());
      ds.finish()
  }
}
pub enum QuellenEintragOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Ein Eintrag des Batches: genau eine Quelle mit genau ihrem aktuellen Frame.
pub struct QuellenEintrag<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for QuellenEintrag<'a> {
  type Inner = QuellenEintrag<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> QuellenEintrag<'a> {
  pub const VT_QUELLE: ::flatbuffers::VOffsetT = 4;
  pub const VT_FRAME: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    QuellenEintrag { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args QuellenEintragArgs<'args>
  ) -> ::flatbuffers::WIPOffset<QuellenEintrag<'bldr>> {
    let mut builder = QuellenEintragBuilder::new(_fbb);
    if let Some(x) = args.frame { builder.add_frame(x); }
    if let Some(x) = args.quelle { builder.add_quelle(x); }
    builder.finish()
  }


  #[inline]
  pub fn quelle(&self) -> Adresse<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Adresse>>(QuellenEintrag::VT_QUELLE, None).unwrap()}
  }
  #[inline]
  pub fn frame(&self) -> Frame<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Frame>>(QuellenEintrag::VT_FRAME, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for QuellenEintrag<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Adresse>>("quelle", Self::VT_QUELLE, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Frame>>("frame", Self::VT_FRAME, true)?
     .finish();
    Ok(())
  }
}
pub struct QuellenEintragArgs<'a> {
    pub quelle: Option<::flatbuffers::WIPOffset<Adresse<'a>>>,
    pub frame: Option<::flatbuffers::WIPOffset<Frame<'a>>>,
}
impl<'a> Default for QuellenEintragArgs<'a> {
  #[inline]
  fn default() -> Self {
    QuellenEintragArgs {
      quelle: None, // required field
      frame: None, // required field
    }
  }
}

pub struct QuellenEintragBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> QuellenEintragBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_quelle(&mut self, quelle: ::flatbuffers::WIPOffset<Adresse<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Adresse>>(QuellenEintrag::VT_QUELLE, quelle);
  }
  #[inline]
  pub fn add_frame(&mut self, frame: ::flatbuffers::WIPOffset<Frame<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Frame>>(QuellenEintrag::VT_FRAME, frame);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> QuellenEintragBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    QuellenEintragBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<QuellenEintrag<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, QuellenEintrag::VT_QUELLE,"quelle");
    self.fbb_.required(o, QuellenEintrag::VT_FRAME,"frame");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for QuellenEintrag<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("QuellenEintrag");
      ds.field("quelle", &self.quelle());
      ds.field("frame", &self.frame());
      ds.finish()
  }
}
pub enum FeatureBatchOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Der Wurzeltyp (§33.1, Pruefbericht Befund D):
///
///   "Ein `FeatureBatch` ist eine Liste von `(source, frame)`-Eintraegen mit
///    hoechstens EINEM aktuellen Frame je Quelle. Sonde→Broker ist der
///    Sonderfall mit genau einem Eintrag (Queuecap 2, replace-oldest);
///    nur Broker→Main buendelt die aktuellen Frames mehrerer Sonden."
///
/// Daraus folgt die Regel, die kein Schema ausdruecken kann und deshalb beide
/// Leser tragen: ZWEI EINTRAEGE MIT DERSELBEN `instance_id` SIND UNGUELTIG.
/// Genau deshalb braucht das Format keine zweite Wrapper-Ebene.
///
/// Die Tabelle haelt heute ein einziges Feld. Das ist Absicht und kein
/// Platzhalter: als Tabelle (statt als blosser Vektor-Wurzeltyp) kann sie
/// spaeter Felder bekommen, ohne dass ein alter Leser bricht.
pub struct FeatureBatch<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for FeatureBatch<'a> {
  type Inner = FeatureBatch<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> FeatureBatch<'a> {
  pub const VT_EINTRAEGE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    FeatureBatch { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FeatureBatchArgs<'args>
  ) -> ::flatbuffers::WIPOffset<FeatureBatch<'bldr>> {
    let mut builder = FeatureBatchBuilder::new(_fbb);
    if let Some(x) = args.eintraege { builder.add_eintraege(x); }
    builder.finish()
  }


  #[inline]
  pub fn eintraege(&self) -> ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<QuellenEintrag<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<QuellenEintrag>>>>(FeatureBatch::VT_EINTRAEGE, None).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for FeatureBatch<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<QuellenEintrag>>>>("eintraege", Self::VT_EINTRAEGE, true)?
     .finish();
    Ok(())
  }
}
pub struct FeatureBatchArgs<'a> {
    pub eintraege: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<QuellenEintrag<'a>>>>>,
}
impl<'a> Default for FeatureBatchArgs<'a> {
  #[inline]
  fn default() -> Self {
    FeatureBatchArgs {
      eintraege: None, // required field
    }
  }
}

pub struct FeatureBatchBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FeatureBatchBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_eintraege(&mut self, eintraege: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<QuellenEintrag<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FeatureBatch::VT_EINTRAEGE, eintraege);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FeatureBatchBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FeatureBatchBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<FeatureBatch<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, FeatureBatch::VT_EINTRAEGE,"eintraege");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for FeatureBatch<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("FeatureBatch");
      ds.field("eintraege", &self.eintraege());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `FeatureBatch`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_feature_batch_unchecked`.
pub fn root_as_feature_batch(buf: &[u8]) -> Result<FeatureBatch<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<FeatureBatch>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `FeatureBatch` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_feature_batch_unchecked`.
pub fn size_prefixed_root_as_feature_batch(buf: &[u8]) -> Result<FeatureBatch<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<FeatureBatch>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `FeatureBatch` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_feature_batch_unchecked`.
pub fn root_as_feature_batch_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<FeatureBatch<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<FeatureBatch<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `FeatureBatch` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_feature_batch_unchecked`.
pub fn size_prefixed_root_as_feature_batch_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<FeatureBatch<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<FeatureBatch<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a FeatureBatch and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `FeatureBatch`.
pub unsafe fn root_as_feature_batch_unchecked(buf: &[u8]) -> FeatureBatch<'_> {
  unsafe { ::flatbuffers::root_unchecked::<FeatureBatch>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed FeatureBatch and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `FeatureBatch`.
pub unsafe fn size_prefixed_root_as_feature_batch_unchecked(buf: &[u8]) -> FeatureBatch<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<FeatureBatch>(buf) }
}
pub const FEATURE_BATCH_IDENTIFIER: &str = "NKT3";

#[inline]
pub fn feature_batch_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, FEATURE_BATCH_IDENTIFIER, false)
}

#[inline]
pub fn feature_batch_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, FEATURE_BATCH_IDENTIFIER, true)
}

pub const FEATURE_BATCH_EXTENSION: &str = "nktb";

#[inline]
pub fn finish_feature_batch_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<FeatureBatch<'a>>) {
  fbb.finish(root, Some(FEATURE_BATCH_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_feature_batch_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<FeatureBatch<'a>>) {
  fbb.finish_size_prefixed(root, Some(FEATURE_BATCH_IDENTIFIER));
}
}  // pub mod v3
}  // pub mod nakama

